from exceptions.users_api_client import InvalidUserDataModelDict